### ISSUE TITLE
see xskillscore

### ISSUE THREAD

**Issue by raybellwaves** [axiom-data-science/ocean-model-skill-assessor#23]
Came across this repo. Just in case you aren't aware there is https://github.com/xarray-contrib/xskillscore which may share some similarities with this repo.

**Comment by kthyng** [comment]
@raybellwaves Thank you for the note! I have seen that listed but hadn't clicked on it before. I agree that it would make sense to have the stats part of this package be done using `xskillscore` — have put that as a to do for the future when I'm working on this next. Thanks again!
